package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.EmpProj;
import model.Employee;
import model.ExtendedEmpProj;
import model.Project;

/**
 *
 * @author Dell
 */
public class MainFrame extends FrameForm {

    private Mode selectedMode;
    private JTextField[] foreignFields;
    private JTextField[] nativeFields;
    private ExtendedEmpProj xEmpProj;
    private DefaultTableModel tableModel;
    private boolean tableClicked = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.xEmpProj = new ExtendedEmpProj();

        this.nativeFields = new JTextField[]{txtEmpNo, txtProjId, txtLocation, txtWeeksProj};
        this.foreignFields = new JTextField[]{txtEmpName, txtDept, txtProjStartDate};
        initComponents();
        this.tableModel = (DefaultTableModel) jTable1.getModel();

        setMode(Mode.DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addModeButton = new javax.swing.JButton();
        editModeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        informationLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDept = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProjId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProjStartDate = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWeeksProj = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Company's tasks made till now:");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Employee's name", "department", "Project's id", "Project's start date", "Location", "Weeks of the project"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addModeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addModeButton.setText("Adding mode");
        addModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModeButtonActionPerformed(evt);
            }
        });

        editModeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editModeButton.setText("Editing Mode");
        editModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editModeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(261, 571));

        informationLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        informationLabel.setText("Information details");

        addButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Employee's no.");

        txtEmpNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmpNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmpNoFocusLost(evt);
            }
        });
        txtEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNoActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Employee's name");

        txtEmpName.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Department");

        txtDept.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Project's id");

        txtProjId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProjIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProjIdFocusLost(evt);
            }
        });
        txtProjId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjIdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Project's start date");

        txtProjStartDate.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Location");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Weeks of the project");

        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmpNo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmpName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDept))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProjId))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProjStartDate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLocation))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeeksProj)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(informationLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProjStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtWeeksProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNoActionPerformed
        System.out.println("txtEmpNoActionPerformed");
        if (selectedMode.equals(Mode.ADDING)) {
            try {
                Employee e = new Employee().getFromNo(Integer.parseInt(txtEmpNo.getText()));
                txtEmpName.setText(e.getEmpName());
                txtDept.setText(e.getDept());
                xEmpProj.setEmployee(e);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                System.err.println(ex.getMessage());
            }
            txtEmpNo.setText(String.valueOf(xEmpProj.getEmpNo()));
        }
    }//GEN-LAST:event_txtEmpNoActionPerformed

    private void txtEmpNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpNoFocusLost
        System.out.println("txtEmpNoFocusLost");
        txtEmpNoActionPerformed(null);
    }//GEN-LAST:event_txtEmpNoFocusLost

    private void txtEmpNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpNoFocusGained
        System.out.println("txtEmpNoFocusGained");
    }//GEN-LAST:event_txtEmpNoFocusGained

    private void txtProjIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjIdActionPerformed
        System.out.println("txtProjIdActionPerformed");
        if (selectedMode.equals(Mode.ADDING)) {
            try {
                Project p = new Project().getFromId(txtProjId.getText());
                txtProjStartDate.setText(p.getProjStartDate());
                xEmpProj.setProject(p);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtProjId.setText(xEmpProj.getProjId());
        }
    }//GEN-LAST:event_txtProjIdActionPerformed

    private void txtProjIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProjIdFocusLost
        System.out.println("txtProjIdFocusLost");
        txtProjIdActionPerformed(null);
    }//GEN-LAST:event_txtProjIdFocusLost

    private void txtProjIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProjIdFocusGained
        System.out.println("txtProjIdFocusGained");
    }//GEN-LAST:event_txtProjIdFocusGained

    private void addModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModeButtonActionPerformed
        setMode(Mode.ADDING);
    }//GEN-LAST:event_addModeButtonActionPerformed

    private void editModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editModeButtonActionPerformed
        setMode(Mode.EDITING);
    }//GEN-LAST:event_editModeButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        System.out.println("deleting...");
        xEmpProj = copyFields();
        int option = JOptionPane.showConfirmDialog(this, Messages.CONFIRM_DELETE, Messages.TITLE_CONFIRM_DELETE, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (option != JOptionPane.YES_OPTION) {
            return;
        }
        setMode(Mode.CONNECTING);
        try {
            xEmpProj.getEmpProj().dbDelete();

            updateTable();
            JOptionPane.showMessageDialog(this, Messages.SUCCESSFUL_UPDATE);
            txtClear();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        setMode(Mode.EDITING);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tableClicked = true;
        int selectedIndex = jTable1.getSelectedRow();

        xEmpProj = new ExtendedEmpProj();
        xEmpProj.setEmpNo((int) tableModel.getValueAt(selectedIndex, 0));
        xEmpProj.setEmpName((String) tableModel.getValueAt(selectedIndex, 1));
        xEmpProj.setDept((String) tableModel.getValueAt(selectedIndex, 2));
        xEmpProj.setProjId((String) tableModel.getValueAt(selectedIndex, 3));
        xEmpProj.setProjStartDate((String) tableModel.getValueAt(selectedIndex, 4));
        xEmpProj.setLocation((String) tableModel.getValueAt(selectedIndex, 5));
        xEmpProj.setWeeksProj((int) tableModel.getValueAt(selectedIndex, 6));

        System.out.println(xEmpProj.toString());
        deleteButton.setEnabled(true);
        editButton.setEnabled(true);

        if (selectedMode.equals(Mode.ADDING) || selectedMode.equals(Mode.EDITING)) {
            pasteSelected();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        jTable1MouseClicked(null);
    }//GEN-LAST:event_jTable1KeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        System.out.println("Adding...");
        xEmpProj = copyFields();
        if (!xEmpProj.isValid()) {
            JOptionPane.showMessageDialog(this, Messages.INVALID_INPUT, Messages.TITLE_INVALID_INPUT, JOptionPane.ERROR_MESSAGE);
            return;
        }
        setMode(Mode.CONNECTING);
        try {
            xEmpProj.getEmpProj().dbInsert();

            updateTable();
            JOptionPane.showMessageDialog(this, Messages.SUCCESSFUL_UPDATE);
            txtClear();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        setMode(Mode.ADDING);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        System.out.println("Editing...");
        xEmpProj = copyFields();
        if (!xEmpProj.isValid()) {
            JOptionPane.showMessageDialog(this, Messages.INVALID_INPUT, Messages.TITLE_INVALID_INPUT, JOptionPane.ERROR_MESSAGE);
            return;
        }
        setMode(Mode.CONNECTING);
        try {
            xEmpProj.getEmpProj().dbUpdate();

            updateTable();
            JOptionPane.showMessageDialog(this, Messages.SUCCESSFUL_UPDATE);
            txtClear();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        setMode(Mode.EDITING);
    }//GEN-LAST:event_editButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setMode(Mode.DEFAULT);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addModeButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editModeButton;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtProjId;
    private javax.swing.JTextField txtProjStartDate;
    private javax.swing.JTextField txtWeeksProj;
    // End of variables declaration//GEN-END:variables

    void updateTable() {
        System.out.println("Updating table");
        tableModel.setRowCount(0);

        ArrayList<ExtendedEmpProj> results = null;
        try {
            results = xEmpProj.getResultSet();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (ExtendedEmpProj xep : results) {
            Object[] rowData = {
                xep.getEmpNo(),
                xep.getEmpName(),
                xep.getDept(),
                xep.getProjId(),
                xep.getProjStartDate(),
                xep.getLocation(),
                xep.getWeeksProj()
            };
            tableModel.addRow(rowData);
        }
    }

    private void pasteSelected() {
        if (!xEmpProj.isValid()) {
            System.out.println("Not valid to paste");
            return;
        }
        System.out.println("Pasting");
        txtEmpNo.setText(String.valueOf(xEmpProj.getEmpNo()));
        txtEmpName.setText(xEmpProj.getEmpName());
        txtDept.setText(xEmpProj.getDept());
        txtProjId.setText(xEmpProj.getProjId());
        txtProjStartDate.setText(xEmpProj.getProjStartDate());
        txtLocation.setText(xEmpProj.getLocation());
        txtWeeksProj.setText(String.valueOf(xEmpProj.getWeeksProj()));
    }

    private ExtendedEmpProj copyFields() {
        ExtendedEmpProj xep = new ExtendedEmpProj();
        xep.setEmpNo(Integer.parseInt(txtEmpNo.getText()));
        xep.setEmpName(txtEmpName.getText());
        xep.setDept(txtDept.getText());
        xep.setProjId(txtProjId.getText());
        xep.setProjStartDate(txtProjStartDate.getText());
        xep.setLocation(txtLocation.getText());
        xep.setWeeksProj(Integer.parseInt(txtWeeksProj.getText()));
        return xep;
    }

    private void setMode(Mode mode) {
        System.out.println("Mode Changed");
        boolean isDefault = mode.equals(Mode.DEFAULT);
        boolean isAdding = mode.equals(Mode.ADDING);
        boolean isEditing = mode.equals(Mode.EDITING);
        boolean isConnecting = mode.equals(Mode.CONNECTING);

        // jPanel1 (DEFAULT):
        jPanel2.setVisible(!isDefault);
        jSplitPane1.setDividerLocation(-1);

        for (java.awt.Component component : jPanel1.getComponents()) {
            if (component instanceof JButton) {
                ((JButton) component).setEnabled(!isConnecting);
            }
        }

        // jPanel2 (EDITING / ADDING):
        for (java.awt.Component component : jPanel2.getComponents()) {
            if (component instanceof JButton) {
                ((JButton) component).setEnabled(!isConnecting);
            }
        }

        txtEmpNo.setEnabled(isAdding);
        txtProjId.setEnabled(isAdding);
        txtLocation.setEnabled(isAdding || isEditing);
        txtWeeksProj.setEnabled(isAdding || isEditing);

        deleteButton.setEnabled(false);
        if (isAdding) {
            informationLabel.setText("Adding mode:");
            addButton.setVisible(true);
            editButton.setVisible(false);
        } else if (isEditing) {
            informationLabel.setText("Editing mode:");
            editButton.setVisible(true);
            addButton.setVisible(false);

            editButton.setEnabled(tableClicked);
            pasteSelected();
        }

        selectedMode = mode;

        if (!isConnecting) {
            updateTable();
        }
    }

    private void txtClear() {
        System.out.println("txtClear");
        for (java.awt.Component component : jPanel2.getComponents()) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }
        tableClicked = false;
        xEmpProj = new ExtendedEmpProj();
    }
}
